 <!--Ovo je content container-->
 <div id="main-container-right">
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
     <?php include('modals/car-item.php')?>
</div>